source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KnowledgeCheck_Example', :exclusive => true do
  pod "KnowledgeCheck", :path => "../"
end

target 'KnowledgeCheck_Tests', :exclusive => true do
  pod "KnowledgeCheck", :path => "../"

  
end
